Restructure everything
sw814f21/filter_xml pull request #21
Opened 2021-04-20 12:03 UTC by NicklasHugoy

2021-04-20 12:52 UTC, Badgie requested changes
Few comments and some other things.

---

This is not C# >: ⁽
Rename the dir to `filter_xml`.

---

In `data_outputter.py` (could not comment as there are no changes):
While this PR does not change anything here, there are some linting errors and type hints that need fixing.
- 2 newlines between classes/functions
- 1 newline between methods
- The `write` method of the base class has a param with a different name from the inherited classes. These should all be the same.
    - The `write` method expects a `dict`, but most (if not all) of the time we send a `list`. I'd suggest changing the type hint to `Union[dict, list]`, where union is from the `typing` module.
- `should_send_to_db` in `get_outputter` needs a type hint

---

Since we are changing this to a package, you should make an `__init__.py` file in the package dir:
- define the argparser and its arguments globally
- make a `run()` function that parses the args and runs collection
Then you can change `run.py` (of course while adhering to the suggested directory name change) to
```py
from src import run

if __name__ == '__main__':
    run()
```

2021-04-20 12:52 UTC, Badgie commented on src/data_handler.py
> +        self.dataProcessor = DataProcessor(sample_size, skip_scrape, outputter)
_

2021-04-20 12:52 UTC, Badgie commented on src/smiley_extractor.py
> +            f.write(json.dumps(res, indent=4, sort_keys=True))
Why is this static? Induces unnecessary calls through the class rather than the instance

2021-04-20 12:52 UTC, Badgie commented on src/smiley_extractor.py
> +            f.write(json.dumps(res, indent=4, sort_keys=True))
If you want them to be callable without creating an instance, make this a class method.

2021-04-20 12:52 UTC, Badgie commented on src/data_processor.py
> +class DataProcessor():
No need for `()`

2021-04-20 12:52 UTC, Badgie commented on src/smiley_extractor.py
> +            f.write(res.content.decode('utf-8'))
Same comment as the other method in this file

2021-04-21 07:52 UTC, NicklasHugoy commented on src/data_handler.py
> +        self.dataProcessor = DataProcessor(sample_size, skip_scrape, outputter)
What's the problem?

2021-04-21 08:26 UTC, Badgie commented on src/data_handler.py
> +        self.dataProcessor = DataProcessor(sample_size, skip_scrape, outputter)
`self.dataProcessor`

2021-04-21 09:09 UTC, Badgie approved these changes

2021-04-21 09:09 UTC, merged