Add blacklist file handler
sw814f21/filter_xml pull request #28
Opened 2021-04-22 12:56 UTC by NicklasHugoy

2021-04-26 13:03 UTC, thorulf4 approved these changes
Thorulf is having existential crisis about how to write code

2021-04-27 09:46 UTC, Badgie requested changes

2021-04-27 09:46 UTC, Badgie commented on filter_xml/data_processor.py
> +                if not temp_file.contains(restaurant['navnelbnr']):
`restaurant.name_seq_nr`

2021-04-27 11:07 UTC, Badgie approved these changes
:shipit:

2021-04-27 11:09 UTC, merged